name: GitHub Security Alerts for Jira

on:
  # schedule:
  #   - cron:  '*/15 * * * *'
  push
jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://manthansshah.atlassian.net
          JIRA_USER: manthan.shah@galepartners.com
          JIRA_PROJECT: PROJ
          JIRA_ISSUE_TYPE: Security
          JIRA_WATCHERS: manthan.shah@galepartners.com
          JIRA_RESTRICTED_COMMENT_ROLE: Administrators
