name: GitHub Security Alerts for Jira

on:
  # schedule:
  #   - cron:  '*/15 * * * *'
  push
jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: gale43/reload-github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://manthansshah.atlassian.net
          JIRA_USER: manthan.shah@galepartners.com
          JIRA_PROJECT: DESK
          JIRA_ISSUE_TYPE: Task
          JIRA_WATCHERS: manthan.shah@galepartners.com
          JIRA_COMPONENT: TestComponent
          #JIRA_RESTRICTED_COMMENT_ROLE: Administrators
